#!/bin/bash

export TMPDIR="/tmp/burncd-$$"
export INCDIR="#PREFIX#/share/convmedia/includes"
export CHARSET="UTF-8"
export CD_DEVICE="/dev/cdrom"

if [ ! -d $TMPDIR ]; then
	mkdir "$TMPDIR"
else
	rm -rf "$TMPDIR"
	mkdir "$TMPDIR"
fi

if [ -f /etc/convmedia/burncd.conf ]; then
	source /etc/convmedia/burncd.conf
else
	echo "Can't load configuration, exiting."
	exit 1
fi

if [ -f $INCDIR/generic-functions.shlib -a -f $INCDIR/audio-functions.shlib ]; then
  source $INCDIR/generic-functions.shlib
  source $INCDIR/audio-functions.shlib
else
  echo "Can't load functions, exiting."
  exit 1
fi

help() {
  echo "burnaudiocd: An extra-sane audio CD burning application."
  echo
  echo "Usage: $0 [OPTIONS]"
  echo
  echo "Options:"
	echo "-a: Audio filters to use."
	echo "-r: Resample input audio to the specified sampling rate, such as 44100."
	echo "-d: CD-Rom device node to use (default /dev/cdrom)."
	echo "-h: Print this help."
	rm -rf "$TMPDIR"
	exit 0
}

while getopts 'a:r:d:h' z; do
  case "$z" in
  a)
    export AF="-af $OPTARG"
  ;;
  d)
    export CD_DEVICE="$OPTARG"
  ;;
  r)
    export RESAMPLE="$OPTARG"
  ;;
	h)
		help
	;;
	esac
done
shift $(($OPTIND-1))

if [ -z $CD_DEVICE ]; then
	help
fi

if [ -n "$RESAMPLE" -a -n "$AF" ]; then
	AF="$AF,resample=$RESAMPLE"
	export MPLAYER_OPTS="$MPLAYER_OPTS -srate $RESAMPLE $AF"
elif [ -n "$RESAMPLE" -a -z "$AF" ]; then
	AF="-af resample=$RESAMPLE"
	export MPLAYER_OPTS="$MPLAYER_OPTS -srate $RESAMPLE $AF"
elif [ -z "$RESAMPLE" -a -n "$AF" ]; then
	export MPLAYER_OPTS="$MPLAYER_OPTS $AF"
fi

for i in "$@"; do
	if [ -f "$i" ]; then
		((N++))
		echo "Decoding ${i}..."
		if [ -z "`file -b "$i" | grep "WAVE audio"`" ]; then
			decode_audio_file "$i" "${TMPDIR}"/${N}.wav
		else
			cp "$i" "${TMPDIR}"/${N}.wav
		fi
		echo "${TMPDIR}"/${N}.wav >> "${TMPDIR}"/list.txt
	fi
done

for i in `cat "${TMPDIR}"/list.txt`; do
	export LIST="$LIST $i"
done

cdrecord dev=$CD_DEVICE -v -audio -pad $LIST

rm -rf "$TMPDIR"
