#!/bin/bash

export TMPDIR="/tmp/convavsbatch-$$"
export INCDIR="/usr/local/share/convmedia/includes"
export CHARSET="UTF-8"
export VERBOSE="1"

# Load required functions and the configuration file.
if [ -f $INCDIR/generic-functions.shlib -a -f $INCDIR/container-functions.shlib \
	-a -f $INCDIR/audio-functions.shlib -a -f $INCDIR/video-functions.shlib \
	-a -f /usr/local/share/convmedia/frontend-includes/convavs.shlib ]; then
		source $INCDIR/generic-functions.shlib
		source $INCDIR/container-functions.shlib
		source $INCDIR/audio-functions.shlib
		source $INCDIR/video-functions.shlib
		source /usr/local/share/convmedia/frontend-includes/convavs.shlib
else
		echo "Can't load functions, exiting."
		exit 1
fi

help() {
	echo "convavs-batch: An extra-insane Video transcoding application that works with AviSynth through wine in batch."
	echo
	echo "Usage: $0 [OPTIONS] FILE FILE FILE"
	echo
	echo "Supported video codecs: h264, mpeg4"
	echo "Supported audio codecs: vorbis, mp3, aac-lc, aac-hev1, aac-hev2, flac"
	echo "Supported container formats: mkv, mp4"
	echo
	echo "Script variables:"
	echo
	echo "INPUT: Input AviSynth script. Required"
	echo "OUTPUT: Output file. Required"
	echo "AUDIO_FILE: Input audio file. Required"
	echo "DELAY: Delay for the input audio file."
	echo "CONTAINER: Container format of the finished encoding."
	echo "SUBTITLE: Subtitle file to include, must be containable in container format."
	echo "VCODEC: Video codec."
	echo "ACODEC: Audio codec."
	echo "AF: Audio filters to use, must be filter supported by mplayer."
	echo "VF: Video filters to use, must be filter supported by mencoder."
	echo "RESAMPLE: Resample audio to specified samplerate."
	echo "VBITRATE: Video bitrate."
	echo "AQUALITY: Audio quality."
	echo "PASS: Number of encoding passes."
	echo "TURBO: Enable or disable turbo, decreased quality on in exchange for speed."
	echo "LIVEACTION: Enable or disable live-action content mode with MPEG4."
	echo "CARTOON: Enable or disable cartoon content mode with MPEG4."
	echo "USEOGGENC2: Enable or disable the usage of Oggenc2, if it exists."
	echo
	echo "Notes:"
	echo "convavs-batch requires avs2yuv.exe (http://akuvian.org/src/avisynth/avs2yuv/) to be placed in /usr/local/share/convmedia/bin in"
	echo "order to operate."
	echo
	echo "You should really use AviSynth filters, as most tend to be much more flexible and powerful than mplayer filters."
	echo
	echo "MP4 does NOT support multiple audio tracks, do not bother ripping the extract tracks as only the first will be used."
	echo "MP4 does NOT support Vorbis audio tracks, this is due to the MP4 standard and only certain software/hardware would be"
	echo "able to play such files, so Vorbis audio tracks will throw an error when used with MP4."
	rm -rf "$TMPDIR"
	exit 0
}

if [ -z "$1" ]; then
 help
fi

if [ -z "`which wine`" ]; then
	die "Wine is not installed, convavs requires wine to be installed to operate."
fi

if [ ! -f /usr/local/share/convmedia/bin/avs2yuv.exe ]; then
	die "Avs2yuv.exe is not in /usr/local/share/convmedia/bin, convavs requires avs2yuv to operate."
fi

for i in $@; do
	if [ -d "$TMPDIR" ]; then
		rm -rf "$TMPDIR"
		mkdir -p "$TMPDIR"
	else
		mkdir -p "$TMPDIR"
	fi

	SUBTITLE=""
	CONTAINER="mkv"
	VCODEC="h264"
	ACODEC="vorbis"
	AF=""
	VF=""
	RESAMPLE=""
	VBITRATE="900"
	AQUALITY="3"
	PASS="1"
	TURBO=""
	LIVEACTION=""
	CARTOON=""
	USEOGGENC2="1"
	DELAY=""

	. "$i"

	if [ -z "$OUTPUT" ]; then
		help
	elif [ -z "$AUDIO_FILE" ]; then
		help
	elif [ $CONTAINER = "mp4" -a $ACODEC = "vorbis" ]; then
		error "Please select another audio codec besides Vorbis!"
		die "MP4 files with Vorbis audio cannot be played back properly on standards-compliant software or hardware!"
	fi

	if [ -n "$DELAY" ]; then
		export AUDIO_DELAY="$(echo "$DELAY * 1000" | bc)"
		unset DELAY
	else
		export AUDIO_DELAY="0"
		unset DELAY
	fi

	if [ -f "$INPUT" -a -f "$AUDIO_FILE" ]; then
		convertavs "$INPUT"
	else
		die "No input video script or audio file!"
	fi
done
