#!/bin/sh

export TMPDIR="/tmp/convcd-$$"
export INCDIR="/usr/local/share/convmedia/includes"
export CHARSET="UTF-8"
export VERBOSE="1"
export INPUT_IS_WAV="1"

if [ ! -d $TMPDIR ]; then
	mkdir $TMPDIR
else
	rm -rf $TMPDIR
	mkdir $TMPDIR
fi

if [ -f /etc/convmedia/convcd.conf ]; then
	source /etc/convmedia/convcd.conf
else
	echo "Can't load configuration, exiting."
	exit 1
fi

if [ -f $INCDIR/generic-functions.shlib -a -f $INCDIR/container-functions.shlib -a -f $INCDIR/audio-functions.shlib ]; then
	source $INCDIR/generic-functions.shlib
	source $INCDIR/container-functions.shlib
	source $INCDIR/audio-functions.shlib
else
	echo "Can't load functions, exiting."
	exit 1
fi

set_masks() {
	# Export title/artist/album/tracknum, then change FILE_MASK accordingly.
	export TITLE="`grep "${N}:" ${TMPDIR}/tracks.txt | cut -d: -f2 | sed 's^&^And^g'`"
	export ARTIST="`grep "${N}:" ${TMPDIR}/tracks-artists.txt | cut -d: -f2 | sed 's^&^And^g'`"
	export ALBUM="`cat ${TMPDIR}/album.txt | grep "album:" | cut -d: -f2 | sed 's^&^And^g'`"
	export YEAR="`cat ${TMPDIR}/album.txt | grep "year:" | cut -d: -f2`"
	export TRACKNUM="$I"
	export ORIG_FMASK="$FILE_MASK"
	export ORIG_DMASK="$DIR_MASK"
	export FILE_MASK="`echo "$FILE_MASK" | sed "s^%TITLE^$TITLE^g" | sed "s^%ARTIST^$ARTIST^g" | sed "s^%ALBUM^$ALBUM^g" | sed "s:%TRACKNUM:$TRACKNUM:g" | \
		sed "s:%YEAR:$TRACK:g"`"
	export DIR_MASK="`echo "$DIR_MASK" | sed "s^%TITLE^$TITLE^g" | sed "s^%ARTIST^$ARTIST^g" | sed "s^%ALBUM^$ALBUM^g" | sed "s:%TRACKNUM:$TRACKNUM:g" | \
		sed "s:%YEAR:$TRACK:g"`"
}

restore_masks() {
	unset TITLE ARTIST ALBUM TRACKNUM
	export FILE_MASK="$ORIG_FMASK"
	export DIR_MASK="$ORIG_DMASK"
}

help() {
	echo "convcd: An extra-sane audio CD ripper."
	echo
	echo "Usage: $0 [OPTIONS]"
	echo
	echo "Supported audio formats: vorbis, mp3, aac-lc, aac-main, aac-ltp, aac-hev1, aac-hev2, flac"
	echo
	echo "Options:"
	echo "-f: Format you want the CD to be ripped to."
	echo "-q: Encoding quality, highest quality is 10, lowest is 1."
	echo "-a: Audio filters to use."
	echo "-r: Resample input audio to the specified sampling rate, such as 44100."
	echo "-n: When encoding to AAC-LC, prefer Nero's encoder over faac if available."
	echo "-d: CD-Rom device node to use."
	echo "-i: Interactive mode, convcd may prompt you to change certain things, such as metadata."
	echo "-m: Multi-artist mode, use this for CD's that have multiple artists rather than one."
	echo "-b: Enable debugging mode (set -e -x)."
	echo "-h: Print this help."
	rm -rf $TMPDIR
	exit 0
}

while getopts 'f:a:q:r:d:nbhmi' z; do
	case "$z" in
	f)
		export ACODEC="$OPTARG"
	;;
	a)
		export AF="-af $OPTARG"
	;;
	q)
		export AQUALITY="$OPTARG"
	;;
	d)
		export CD_DEVICE="$OPTARG"
	;;
	b)
		set -e -x
	;;
	r)
		export RESAMPLE="$OPTARG"
	;;
	n)
		export USENEROAAC="1"
		export USEOGGENC2="1"
	;;
	i)
		export INTERACTIVE="1"
	;;
	m)
		export MULTI_ARTIST="1"
	;;
	h)
		help
	;;
 esac
done
shift $(($OPTIND-1))

if [ -z $ACODEC ]; then
	help
fi

if [ -n "$RESAMPLE" -a -n "$AF" ]; then
	AF="$AF,resample=$RESAMPLE"
	export MPLAYER_OPTS="$MPLAYER_OPTS -srate $RESAMPLE $AF"
elif [ -n "$RESAMPLE" -a -z "$AF" ]; then
	AF="-af resample=$RESAMPLE"
	export MPLAYER_OPTS="$MPLAYER_OPTS -srate $RESAMPLE $AF"
elif [ -z "$RESAMPLE" -a -n "$AF" ]; then
	export MPLAYER_OPTS="$MPLAYER_OPTS $AF"
fi

export PARANOIA_OPTS="--never-skip=40 -d $CD_DEVICE"
export CDDISCID_OPTS="$CD_DEVICE"

echo "Retrieving information about this CD from CDDB..."
cddb_query_info
export ALBUM="`cat ${TMPDIR}/album.txt | grep "album:" | cut -d: -f2 | sed 's^&^And^g'`"
export YEAR="`cat ${TMPDIR}/album.txt | grep "year:" | cut -d: -f2`"
echo "Album: $ALBUM" >> $TMPDIR/album-info.txt
echo "Year of release: $YEAR" >> $TMPDIR/album-info.txt
unset ALBUM
for i in `seq 0 $TRACKS`; do
	if [ ! "`echo -n "$i" | wc -m`" = "2" ]; then
		export N="0${i}"
	else
		export N="$i"
	fi
	set_masks
	echo "Track $N: $TITLE by $ARTIST" >> $TMPDIR/album-info.txt
	restore_masks
done
cat $TMPDIR/album-info.txt

if [ -n "$INTERACTIVE" ]; then
	echo -n "Do you want to edit the song titles, artist(s) and album name information now? (y/n) "; read answer
	if [ "$answer" = "y" ]; then
		$EDITOR ${TMPDIR}/tracks.txt
		$EDITOR ${TMPDIR}/tracks-artists.txt
		$EDITOR ${TMPDIR}/album.txt
		# Recalculate number of tracks to rip by using tracks.txt.
		export TRACKS="`cat ${TMPDIR}/tracks.txt | wc -l`"
		export TRACKS="`expr $TRACKS - 1`"
	fi
fi

for i in `seq 0 $TRACKS`; do
	if [ ! "`echo -n "$i" | wc -m`" = "2" -a ! "$i" = "9" ]; then
		export I="$i"
		((I++))
		export I="0${I}"
		export N="0${i}"
	else
		export I="${i}"
		((I++))
		export N="$i"
	fi

	set_masks

	if [ ! -d "$DIR_MASK" ]; then
		mkdir -p "$DIR_MASK"
	fi

	cdparanoia ${PARANOIA_OPTS} $I "${TMPDIR}/${FILE_MASK}.wav"

	case $ACODEC in
	vorbis)
		echo "Encoding ${FILE_MASK}.wav to ${ACODEC}..."
		audio_encode $ACODEC "${TMPDIR}/${FILE_MASK}.wav" "${DIR_MASK}/${FILE_MASK}.ogg"
		echo "Setting metatags for ${DIR_MASK}/${FILE_MASK}.ogg"
		set_common_metatags ogg "${DIR_MASK}/${FILE_MASK}.ogg"
		echo
	;;
	aac-*)
		echo "Encoding ${FILE_MASK}.wav to ${ACODEC}..."
		audio_encode $ACODEC "${TMPDIR}/${FILE_MASK}.wav" "${DIR_MASK}/${FILE_MASK}.mp4"
		echo "Setting metatags for ${DIR_MASK}/${FILE_MASK}.mp4"
		set_common_metatags mp4 "${DIR_MASK}/${FILE_MASK}.mp4"
		echo
	;;
	mp3)
		echo "Encoding ${FILE_MASK}.wav to ${ACODEC}..."
		audio_encode $ACODEC "${TMPDIR}/${FILE_MASK}.wav" "${DIR_MASK}/${FILE_MASK}.mp3"
		echo "Setting metatags for ${DIR_MASK}/${FILE_MASK}.mp3"
		set_common_metatags id3 "${DIR_MASK}/${FILE_MASK}.mp3"
		echo
	;;
	flac)
		echo "Encoding ${FILE_MASK}.wav to ${ACODEC}..."
		audio_encode $ACODEC "${TMPDIR}/${FILE_MASK}.wav" "${DIR_MASK}/${FILE_MASK}.flac"
		echo "Setting metatags for ${DIR_MASK}/${FILE_MASK}.flac"
		set_common_metatags flac "${DIR_MASK}/${FILE_MASK}.flac"
		echo
	;;
	esac
	restore_masks
done

rm -rf "$TMPDIR"
if [ -n "$EJECT" ]; then
	eject "$CD_DEVICE"
fi
