#!/bin/bash

# Make sure we use UTF-8!
export CHARSET="UTF-8"
export INCDIR="#PREFIX#/share/convmedia/includes"
export THREADS="$(cat /proc/cpuinfo | grep processor | wc -l)"

if [ -f /etc/convmedia/convaudio.conf ]; then
		source /etc/convmedia/convaudio.conf
else
		echo "Can't load configuration, exiting."
		exit 1
fi

if [ -f $INCDIR/generic-functions.shlib -a -f $INCDIR/container-functions.shlib \
	-a -f $INCDIR/audio-functions.shlib -a -f #PREFIX#/share/convmedia/frontend-includes/convaudio.shlib ]; then
		source $INCDIR/generic-functions.shlib
		source $INCDIR/container-functions.shlib
		source $INCDIR/audio-functions.shlib
		source #PREFIX#/share/convmedia/frontend-includes/convaudio.shlib
else
		echo "Can't load functions, exiting."
		exit 1
fi

help() {
	echo "convaudio-mt: An extra-sane audio transcoding application (multithreaded)."
	echo
	echo "Usage: $0 [OPTIONS] FILES"
	echo
	echo "Supported formats: vorbis, flac, mp3, aac, aac-lc, aac-hev1, aac-hev2"
	echo
	echo "Options:"
	echo "-f: Format you want the files to be transcoded to."
	echo "-q: Quality scale, highest quality is 10, lowest is 1."
	echo "-a: Audio filters to use."
	echo "-r: Resample input audio to the specified sampling rate, such as 44100."
	echo "-t: Number of threads to utilize for encoding (default auto-detect)."
	echo "-d: Enable debugging mode (set -e -x)."
	echo "-h: Print this help."
	rm -rf $TMPDIR
	exit 0
}

while getopts 'f:a:q:r:t:wdh' z; do
	case "$z" in
	f)
		export OF_IS_SET=1
		export PASS_ARGS="${PASS_ARGS} -f ${OPTARG}"
	;;
	a)
		export PASS_ARGS="${PASS_ARGS} -a ${OPTARG}"
	;;
	q)
		export PASS_ARGS="${PASS_ARGS} -q ${OPTARG}"
	;;
	d)
		set -e -x
	;;
	r)
	  export PASS_ARGS="${PASS_ARGS} -r ${OPTARG}"
	;;
	t)
		if [ -n "$OPTARG" ]; then
			export THREADS="$OPTARG"
		else
			echo "Please supply an argument to -t."
			exit 1
		fi
	;;
	h)
		help
	;;
	esac
done
shift $(($OPTIND-1))

if [ -z "$PASS_ARGS" -a -z "$OF_IS_SET" ]; then
	help
fi

find "$@" -print0 | xargs -0 -n 1 -P $THREADS convaudio $PASS_ARGS
