#!/bin/bash

# Make sure we use UTF-8!
export CHARSET="UTF-8"
export TMPDIR="/tmp/convaudio-$$"
export INCDIR="#PREFIX#/share/convmedia/includes"

if [ -f /etc/convmedia/convaudio.conf ]; then
		source /etc/convmedia/convaudio.conf
else
		echo "Can't load configuration, exiting."
		exit 1
fi

if [ ! -d "$TMPDIR" ]; then
 mkdir -p "$TMPDIR"
else
 rm -rf "$TMPDIR"
 mkdir -p "$TMPDIR"
fi

help() {
	echo "convaudio: An extra-sane audio transcoding application."
	echo
	echo "Usage: $0 [OPTIONS] FILES"
	echo
	echo "Supported formats: vorbis, flac, mp3, aac, aac-lc, aac-hev1, aac-hev2"
	echo
	echo "Options:"
	echo "-t: Number of threads to use for conversion, defaults to auto detection."
	echo "-f: Format you want the files to be transcoded to."
	echo "-q: Quality scale, highest quality is 10, lowest is 1."
	echo "-a: Audio filters to use."
	echo "-r: Resample input audio to the specified sampling rate, such as 44100."
	echo "-d: Enable debugging mode (set -e -x)."
	echo "-h: Print this help."
	rm -rf $TMPDIR
	exit 0
}

while getopts 't:f:a:q:r:wdh' z; do
	case "$z" in
	t)
		export THREADS="$OPTARG"
	;;
	f)
		export OUTPUTFORMAT="$OPTARG"
	;;
	a)
		export AF="-af $OPTARG"
	;;
	q)
		export AQUALITY="$OPTARG"
	;;
	d)
		set -e -x
	;;
	r)
	  export RESAMPLE="$OPTARG"
	;;
	h)
		help
	;;
	esac
done
shift $(($OPTIND-1))

if [ -f $INCDIR/generic-functions.shlib -a -f $INCDIR/container-functions.shlib \
	-a -f $INCDIR/audio-functions.shlib -a -f $INCDIR/thread-functions.shlib \
	-a -f #PREFIX#/share/convmedia/frontend-includes/convaudio.shlib ]; then
		source $INCDIR/generic-functions.shlib
		source $INCDIR/container-functions.shlib
		source $INCDIR/audio-functions.shlib
		source $INCDIR/thread-functions.shlib
		source #PREFIX#/share/convmedia/frontend-includes/convaudio.shlib
else
		echo "Can't load functions, exiting."
		exit 1
fi

if [ -z $OUTPUTFORMAT ]; then
	help
fi

(run_parallel convertaudio "$@")
rm -rf "$TMPDIR"
