#!/bin/bash
# installer
# Written by: predatorfreak

if [ -z "$DESTDIR" ]; then
	DESTDIR=/
fi

if [ -z "$PREFIX" ]; then
	PREFIX=/usr/local/
fi

if [ -f includes/generic-functions.shlib ]; then
	source includes/generic-functions.shlib
else
	echo "Can't load required functions, exiting."
	exit 1
fi

checkdeps()	{
	if [ -z "`which mplayer 2>/dev/null`" -a -z "`which mencoder 2>/dev/null`" ]; then
		warn "MPlayer isn't installed or wasn't built with MEncoder enabled."
		warn "MPlayer/MEncoder are required for anything which decodes or encodes audio/video. However, bcddb/btagger will function without MPlayer/MEncoder."
	fi
	if [ -z "`which MP4Box 2>/dev/null`" ]; then
		warn "Gpac is not installed, this is required for muxing of MP4 streams."
	fi
	if [ -z "`which mkvmerge 2>/dev/null`" ]; then
		warn "mkvtoolnix is not installed, this provides convmedia with the ability to mux Matroska files."
	fi
	if [ -z "`which oggenc 2>/dev/null`" ]; then
		warn "Vorbis-tools is not installed, this provides oggenc which is required for encoding Ogg Vorbis files."
	fi
	if [ -z "`which lame 2>/dev/null`" ]; then
		warn "LAME is not installed, this provides lame, which is required for encoding MP3 files."
	fi
	if [ -z "`which flac 2>/dev/null`" ]; then
		warn "FLAC is not installed, this provides flac, which is required for encoding FLAC files."
	fi
	if [ -z "`which neroAacEnc 2>/dev/null`" ]; then
		warn "Nero Digital AAC is not installed, this provides neroAacEnc, which is required for encoding AAC (LC/HE/HEv2) files."
		warn "Nero Digital AAC can be acquired from: http://www.nero.com/eng/downloads-nerodigital-nero-aac-codec.php"
	fi
	if [ -z "`which bc 2>/dev/null`" ]; then
		warn "bc is not installed, bc is required for on-the-fly bitrate calculation."
	fi
	if [ -z "`which cd-discid 2>/dev/null`" ]; then
		warn "cd-discid is not installed, cd-discid is required for CDDB querying to function."
	fi
	if [ -z "`which cdparanoia 2>/dev/null`" ]; then
		warn "cdparanoia is not installed, cdparanoia is required for ripping CD's with convcd."
	fi
	if [ -z "`which vorbisgain 2>/dev/null`" ]; then
		warn "vorbisgain is not installed, vorbisgain is required to calculate ReplayGain information for Ogg Vorbis files."
	fi
}

if [ ! `whoami` = "root" ]; then
	die "You must be root in order to install convmedia."
fi

case "$1" in
install)
	checkdeps
	if [ ! -d $DESTDIR/$PREFIX/share/convmedia ]; then
		echo "Beginning convmedia installation."
		if [ ! -d $DESTDIR/$PREFIX/bin ]; then
			mkdir -p $DESTDIR/$PREFIX/bin
		fi
		if [ ! -d $DESTDIR/etc/convmedia ]; then
			mkdir -p $DESTDIR/etc/convmedia
		fi
		mkdir -p $DESTDIR/$PREFIX/share/convmedia/{includes,frontend-includes}
		cp config/* /etc/convmedia/
		for i in frontends/*; do
			cp "$i" $DESTDIR/$PREFIX/bin/
			chmod +x $DESTDIR/$PREFIX/bin/`basename "$i"`
			sed -i -e "s:#PREFIX#:$PREFIX:g" $DESTDIR/$PREFIX/bin/`basename "$i"`
		done
		cp frontend-includes/* $DESTDIR/$PREFIX/share/convmedia/frontend-includes/
		cp includes/* $DESTDIR/$PREFIX/share/convmedia/includes/
		echo "Done."
		exit 0
	else
		die "Installer: The directory $PREFIX/share/convmedia already exists, please run ./installer upgrade instead."
	fi
;;
upgrade)
	checkdeps
	if [ -d $DESTDIR/$PREFIX/share/convmedia ]; then
		echo "Beginning convmedia upgrade."
		if [ ! -d $DESTDIR/$PREFIX/bin ]; then
			mkdir -p $DESTDIR/$PREFIX/bin
		fi    
		if [ ! -d $DESTDIR/etc/convmedia ]; then
			mkdir -p $DESTDIR/etc/convmedia
		fi
		mkdir -p $DESTDIR/$PREFIX/share/convmedia/{includes,frontend-includes}
		cp -i config/* /etc/convmedia/
		for i in frontends/*; do
			cp "$i" $PREFIX/bin/
			chmod +x $PREFIX/bin/`basename "$i"`
			sed -i -e "s:#PREFIX#:$PREFIX:g" $DESTDIR/$PREFIX/bin/`basename "$i"`
		done
		cp frontend-includes/* $DESTDIR/$PREFIX/share/convmedia/frontend-includes/
		cp includes/* $DESTDIR/$PREFIX/share/convmedia/includes/
		echo "Done."
		exit 0
	else
		die "Installer: The directory $PREFIX/share/convmedia doesn't exist, please run ./installer install instead."
	fi
;;
*)
	echo "installer -"
	echo "A streamlined installation system for convmedia."
	echo
	echo "Usage: ./installer [OPTION]"
	echo
	echo "Options:"
	echo "install"
	echo "upgrade"
	exit 0
;;
esac
