#!/bin/bash
# installer

if [ -z "$DESTDIR" ]; then
	DESTDIR=/
fi

if [ -z "$PREFIX" ]; then
	PREFIX=/usr/local/
fi

if [ -f includes/generic-functions.shlib ]; then
	source includes/generic-functions.shlib
else
	echo "Can't load required functions, exiting."
	exit 1
fi

checkdeps()	{
	if ! which mplayer &>/dev/null && ! which mencoder &>/dev/null; then
		warn "MPlayer isn't installed or wasn't built with MEncoder enabled."
		warn "MPlayer/MEncoder are required for anything which decodes or encodes audio/video. However, bcddb/btagger will function without MPlayer/MEncoder."
	fi
	if ! which MP4Box &>/dev/null; then
		warn "Gpac is not installed, this is required for muxing of MP4 streams."
	fi
	if which pkg-config &>/dev/null; then
		if ! pkg-config --exists taglib; then
			warn "Taglib is not installed, Taglib is required for reading and writing metatags for audio files."
		fi
	else
		warn "pkg-config is not installed, this is required to check for taglib and build the tagreader/writer binaries, which allow tagging of audio files."
	fi
	if ! which mkvmerge &>/dev/null; then
		warn "mkvtoolnix is not installed, this provides convmedia with the ability to mux Matroska files."
	fi
	if ! which oggenc &>/dev/null; then
		warn "Vorbis-tools is not installed, this provides oggenc which is required for encoding Ogg Vorbis files."
	fi
	if ! which lame &>/dev/null; then
		warn "LAME is not installed, this provides lame, which is required for encoding MP3 files."
	fi
	if ! which flac &>/dev/null; then
		warn "FLAC is not installed, this provides flac, which is required for encoding FLAC files."
	fi
	if ! which neroAacEnc &>/dev/null; then
		warn "Nero Digital AAC is not installed, this provides neroAacEnc, which is required for encoding AAC (LC/HE/HEv2) files."
		warn "Nero Digital AAC can be acquired from: http://www.nero.com/eng/downloads-nerodigital-nero-aac-codec.php"
	fi
	if ! which bc &>/dev/null; then
		warn "bc is not installed, bc is required for on-the-fly bitrate calculation."
	fi
	if ! which cd-discid &>/dev/null; then
		warn "cd-discid is not installed, cd-discid is required for CDDB querying to function."
	fi
	if ! which cdparanoia &>/dev/null; then
		warn "cdparanoia is not installed, cdparanoia is required for ripping CD's with convcd."
	fi
	if ! which vorbisgain &>/dev/null; then
		warn "vorbisgain is not installed, vorbisgain is required to calculate ReplayGain information for Ogg Vorbis files."
	fi
}

if [ ! `whoami` = "root" ]; then
	die "You must be root in order to install convmedia."
fi

case "$1" in
install)
	checkdeps
	if [ ! -d $DESTDIR/$PREFIX/share/convmedia ]; then
		echo "Beginning convmedia installation."
		if [ ! -d $DESTDIR/$PREFIX/bin ]; then
			mkdir -p $DESTDIR/$PREFIX/bin
		fi
		if [ ! -d $DESTDIR/etc/convmedia ]; then
			mkdir -p $DESTDIR/etc/convmedia
		fi
		mkdir -p $DESTDIR/$PREFIX/share/convmedia/{includes,frontend-includes}
		cp config/* /etc/convmedia/

		for i in frontends/*; do
			cp "$i" $DESTDIR/$PREFIX/bin/
			chmod +x $DESTDIR/$PREFIX/bin/`basename "$i"`
			sed -i -e "s:#PREFIX#:$PREFIX:g" $DESTDIR/$PREFIX/bin/`basename "$i"`
		done
		cp frontend-includes/* $DESTDIR/$PREFIX/share/convmedia/frontend-includes/
		cp includes/* $DESTDIR/$PREFIX/share/convmedia/includes/


		# Detect if tagreader/writer are provided, if not build them ourselves.
		if [ -n "`which pkg-config 2>/dev/null`" ]; then
			if pkg-config --exists taglib && ! which tagreader &>/dev/null && ! which tagwriter &>/dev/null && which g++ &>/dev/null; then
				pushd external &>/dev/null
				echo "Building tagreader and tagwriter."
				for i in *.cpp; do
					g++ `pkg-config --libs --cflags taglib` "$i" -o "$(basename "$i" .cpp)"
					cp "$(basename "$i" .cpp)" $DESTDIR/$PREFIX/bin/
					rm "$(basename "$i" .cpp)"
				done
				popd &>/dev/null
			fi
		fi

		echo "Done."
		exit 0
	else
		die "Installer: The directory $PREFIX/share/convmedia already exists, please run ./installer upgrade instead."
	fi
;;
upgrade)
	checkdeps
	if [ -d $DESTDIR/$PREFIX/share/convmedia ]; then
		echo "Beginning convmedia upgrade."
		if [ ! -d $DESTDIR/$PREFIX/bin ]; then
			mkdir -p $DESTDIR/$PREFIX/bin
		fi    
		if [ ! -d $DESTDIR/etc/convmedia ]; then
			mkdir -p $DESTDIR/etc/convmedia
		fi
		mkdir -p $DESTDIR/$PREFIX/share/convmedia/{includes,frontend-includes}
		cp -i config/* /etc/convmedia/
		for i in frontends/*; do
			cp "$i" $DESTDIR/$PREFIX/bin/
			chmod +x $DESTDIR/$PREFIX/bin/`basename "$i"`
			sed -i -e "s:#PREFIX#:$PREFIX:g" $DESTDIR/$PREFIX/bin/`basename "$i"`
		done

		cp frontend-includes/* $DESTDIR/$PREFIX/share/convmedia/frontend-includes/
		cp includes/* $DESTDIR/$PREFIX/share/convmedia/includes/

		# Detect if tagreader/writer are provided, if not build them ourselves.
		if [ -n "`which pkg-config 2>/dev/null`" ]; then
			if pkg-config --exists taglib && ! which tagreader &>/dev/null && ! which tagwriter &>/dev/null && which g++ &>/dev/null; then
				pushd external
				echo "Building tagreader and tagwriter."
				for i in *.cpp; do
					g++ `pkg-config --libs --cflags taglib` "$i" -o "$(basename "$i" .cpp)"
					cp "$(basename "$i" .cpp)" $DESTDIR/$PREFIX/bin/
					rm "$(basename "$i" .cpp)"
				done
				popd &>/dev/null
			fi
		fi

		echo "Done."
		exit 0
	else
		die "Installer: The directory $PREFIX/share/convmedia doesn't exist, please run ./installer install instead."
	fi
;;
*)
	echo "installer -"
	echo "A streamlined installation system for convmedia."
	echo
	echo "Usage: ./installer [OPTION]"
	echo
	echo "Options:"
	echo "install"
	echo "upgrade"
	exit 0
;;
esac
